# ansible-playbook deploy.yaml -i inventories/prod/hosts --vault-id ~/.tokens/master_id

- hosts: all
  strategy: free
  tasks:

    - name: Render the starbound_server.config files
      template:
        src: starbound_server.config.j2
        dest: '{{ directories_files }}/{{ item.name }}starbound_server.config'
      vars:
        players: '{{ item.permitted }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ directories_files }}/{{ item.name }}starbound_server.config'

    - name: Render docker-compose.yaml & deploy stack
      import_role:
        name: docker-deploy
      vars:
        with_registry: no

    - name: Allow server ports
      ufw:
        rule: allow
        port: "{{ server.port }}"
      vars:
        server: '{{ item }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ item.port }}'
      become: yes

    - name: Reload Firewall and enable at boot
      ufw:
        state: enabled
        policy: deny
      become: yes
